server:
   port: 10010
dubbo:
   application:
      name: angboot-authority-provider
   registry:
      address: zookeeper://127.0.0.1:2181
   protocol:
      name: dubbo
      port: 20880

druid:
   username: jackli
   password: dreamli0812
   url: jdbc:h2:/Users/dreamli/Workspace/MyRepository/angboot/dev-0.2.0/angboot/providers/authority/out/production/resources/angbootdb/AngBoot_db
   driver-class-name: org.h2.Driver
   type: com.alibaba.druid.pool.DruidDataSource
   initialSize: 5
   minIdle: 5
   maxActive: 20
   maxWait: 60000
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: SELECT 1 FROM DUAL
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
   poolPreparedStatements: true
   filters: stat,wall,log4j
   maxPoolPreparedStatementPerConnectionSize: 20
   useGlobalDataSourceStat: true
   connectionProperties: druid.stat.mergeSql
